// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/v1/msg.proto

package corev1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "rain-im-server/protogo/base/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.UUID               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      *v1.UUID               `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      *v1.UUID               `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Seq           uint64                 `protobuf:"fixed64,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *v1.Time               `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *v1.Time               `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_core_v1_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_core_v1_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() *v1.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *Message) GetTargetId() *v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() *v1.Time {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *v1.Time {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_core_v1_msg_proto protoreflect.FileDescriptor

const file_core_v1_msg_proto_rawDesc = "" +
	"\n" +
	"\x11core/v1/msg.proto\x12\acore.v1\x1a\x13tagger/tagger.proto\x1a\x12base/v1/time.proto\x1a\x12base/v1/uuid.proto\"\x87\x03\n" +
	"\aMessage\x126\n" +
	"\x02id\x18\x01 \x01(\v2\r.base.v1.UUIDB\x17\x9a\x84\x9e\x03\x12bun:\"type:uuid,pk\"R\x02id\x12@\n" +
	"\tsource_id\x18\x02 \x01(\v2\r.base.v1.UUIDB\x14\x9a\x84\x9e\x03\x0fbun:\"type:uuid\"R\bsourceId\x12@\n" +
	"\ttarget_id\x18\x03 \x01(\v2\r.base.v1.UUIDB\x14\x9a\x84\x9e\x03\x0fbun:\"type:uuid\"R\btargetId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x06R\x03seq\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12I\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\r.base.v1.TimeB\x1b\x9a\x84\x9e\x03\x16bun:\"type:timestamptz\"R\tcreatedAt\x12I\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\r.base.v1.TimeB\x1b\x9a\x84\x9e\x03\x16bun:\"type:timestamptz\"R\tupdatedAtB{\n" +
	"\vcom.core.v1B\bMsgProtoP\x01Z%rain-im-server/protogo/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_msg_proto_rawDescOnce sync.Once
	file_core_v1_msg_proto_rawDescData []byte
)

func file_core_v1_msg_proto_rawDescGZIP() []byte {
	file_core_v1_msg_proto_rawDescOnce.Do(func() {
		file_core_v1_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_msg_proto_rawDesc), len(file_core_v1_msg_proto_rawDesc)))
	})
	return file_core_v1_msg_proto_rawDescData
}

var file_core_v1_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_v1_msg_proto_goTypes = []any{
	(*Message)(nil), // 0: core.v1.Message
	(*v1.UUID)(nil), // 1: base.v1.UUID
	(*v1.Time)(nil), // 2: base.v1.Time
}
var file_core_v1_msg_proto_depIdxs = []int32{
	1, // 0: core.v1.Message.id:type_name -> base.v1.UUID
	1, // 1: core.v1.Message.source_id:type_name -> base.v1.UUID
	1, // 2: core.v1.Message.target_id:type_name -> base.v1.UUID
	2, // 3: core.v1.Message.created_at:type_name -> base.v1.Time
	2, // 4: core.v1.Message.updated_at:type_name -> base.v1.Time
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_core_v1_msg_proto_init() }
func file_core_v1_msg_proto_init() {
	if File_core_v1_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_msg_proto_rawDesc), len(file_core_v1_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_msg_proto_goTypes,
		DependencyIndexes: file_core_v1_msg_proto_depIdxs,
		MessageInfos:      file_core_v1_msg_proto_msgTypes,
	}.Build()
	File_core_v1_msg_proto = out.File
	file_core_v1_msg_proto_goTypes = nil
	file_core_v1_msg_proto_depIdxs = nil
}
