// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/v1/srv_client.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreConnectRequest) Reset() {
	*x = PreConnectRequest{}
	mi := &file_core_v1_srv_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreConnectRequest) ProtoMessage() {}

func (x *PreConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_srv_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreConnectRequest.ProtoReflect.Descriptor instead.
func (*PreConnectRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_srv_client_proto_rawDescGZIP(), []int{0}
}

type PreConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreConnectResponse) Reset() {
	*x = PreConnectResponse{}
	mi := &file_core_v1_srv_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreConnectResponse) ProtoMessage() {}

func (x *PreConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_srv_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreConnectResponse.ProtoReflect.Descriptor instead.
func (*PreConnectResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_srv_client_proto_rawDescGZIP(), []int{1}
}

var File_core_v1_srv_client_proto protoreflect.FileDescriptor

const file_core_v1_srv_client_proto_rawDesc = "" +
	"\n" +
	"\x18core/v1/srv_client.proto\x12\acore.v1\"\x13\n" +
	"\x11PreConnectRequest\"\x14\n" +
	"\x12PreConnectResponse2X\n" +
	"\rClientService\x12G\n" +
	"\n" +
	"PreConnect\x12\x1a.core.v1.PreConnectRequest\x1a\x1b.core.v1.PreConnectResponse\"\x00B\x81\x01\n" +
	"\vcom.core.v1B\x0eSrvClientProtoP\x01Z%rain-im-server/protogo/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_srv_client_proto_rawDescOnce sync.Once
	file_core_v1_srv_client_proto_rawDescData []byte
)

func file_core_v1_srv_client_proto_rawDescGZIP() []byte {
	file_core_v1_srv_client_proto_rawDescOnce.Do(func() {
		file_core_v1_srv_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_srv_client_proto_rawDesc), len(file_core_v1_srv_client_proto_rawDesc)))
	})
	return file_core_v1_srv_client_proto_rawDescData
}

var file_core_v1_srv_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_srv_client_proto_goTypes = []any{
	(*PreConnectRequest)(nil),  // 0: core.v1.PreConnectRequest
	(*PreConnectResponse)(nil), // 1: core.v1.PreConnectResponse
}
var file_core_v1_srv_client_proto_depIdxs = []int32{
	0, // 0: core.v1.ClientService.PreConnect:input_type -> core.v1.PreConnectRequest
	1, // 1: core.v1.ClientService.PreConnect:output_type -> core.v1.PreConnectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_srv_client_proto_init() }
func file_core_v1_srv_client_proto_init() {
	if File_core_v1_srv_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_srv_client_proto_rawDesc), len(file_core_v1_srv_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_srv_client_proto_goTypes,
		DependencyIndexes: file_core_v1_srv_client_proto_depIdxs,
		MessageInfos:      file_core_v1_srv_client_proto_msgTypes,
	}.Build()
	File_core_v1_srv_client_proto = out.File
	file_core_v1_srv_client_proto_goTypes = nil
	file_core_v1_srv_client_proto_depIdxs = nil
}
