// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_SYSTEM      Platform = 1 // 系统
	Platform_PLATFORM_WEB         Platform = 2 // 网页
	Platform_PLATFORM_ANDROID     Platform = 3 // 安卓
	Platform_PLATFORM_IPHONE      Platform = 4 // 苹果
	Platform_PLATFORM_WINDOWS     Platform = 5 // Windows
	Platform_PLATFORM_MACOS       Platform = 6 // Mac
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_SYSTEM",
		2: "PLATFORM_WEB",
		3: "PLATFORM_ANDROID",
		4: "PLATFORM_IPHONE",
		5: "PLATFORM_WINDOWS",
		6: "PLATFORM_MACOS",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_SYSTEM":      1,
		"PLATFORM_WEB":         2,
		"PLATFORM_ANDROID":     3,
		"PLATFORM_IPHONE":      4,
		"PLATFORM_WINDOWS":     5,
		"PLATFORM_MACOS":       6,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_gateway_v1_gateway_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type Message int32

const (
	Message_MESSAGE_UNSPECIFIED Message = 0
	Message_MESSAGE_SINGLE      Message = 1 // 单发
	Message_MESSAGE_GROUP       Message = 2 // 群发
	Message_MESSAGE_PULL        Message = 3 // 拉取消息
	Message_MESSAGE_RELAY       Message = 4 // TODO:转发消息
	Message_MESSAGE_MULTIPLE    Message = 5 // TODO:多发消息
)

// Enum value maps for Message.
var (
	Message_name = map[int32]string{
		0: "MESSAGE_UNSPECIFIED",
		1: "MESSAGE_SINGLE",
		2: "MESSAGE_GROUP",
		3: "MESSAGE_PULL",
		4: "MESSAGE_RELAY",
	}
	Message_value = map[string]int32{
		"MESSAGE_UNSPECIFIED": 0,
		"MESSAGE_SINGLE":      1,
		"MESSAGE_GROUP":       2,
		"MESSAGE_PULL":        3,
		"MESSAGE_RELAY":       4,
	}
)

func (x Message) Enum() *Message {
	p := new(Message)
	*p = x
	return p
}

func (x Message) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_gateway_proto_enumTypes[1].Descriptor()
}

func (Message) Type() protoreflect.EnumType {
	return &file_gateway_v1_gateway_proto_enumTypes[1]
}

func (x Message) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message.Descriptor instead.
func (Message) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1*\xa0\x01\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPLATFORM_SYSTEM\x10\x01\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x02\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x03\x12\x13\n" +
	"\x0fPLATFORM_IPHONE\x10\x04\x12\x14\n" +
	"\x10PLATFORM_WINDOWS\x10\x05\x12\x12\n" +
	"\x0ePLATFORM_MACOS\x10\x06*n\n" +
	"\aMessage\x12\x17\n" +
	"\x13MESSAGE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eMESSAGE_SINGLE\x10\x01\x12\x11\n" +
	"\rMESSAGE_GROUP\x10\x02\x12\x10\n" +
	"\fMESSAGE_PULL\x10\x03\x12\x11\n" +
	"\rMESSAGE_RELAY\x10\x04B\x94\x01\n" +
	"\x0ecom.gateway.v1B\fGatewayProtoP\x01Z+rain-im-server/protogo/gateway/v1;gatewayv1\xa2\x02\x03GXX\xaa\x02\n" +
	"Gateway.V1\xca\x02\n" +
	"Gateway\\V1\xe2\x02\x16Gateway\\V1\\GPBMetadata\xea\x02\vGateway::V1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(Platform)(0), // 0: gateway.v1.Platform
	(Message)(0),  // 1: gateway.v1.Message
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_v1_gateway_proto_enumTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
