// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gateway/v1/message.proto

package gatewayv1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "rain-im-server/protogo/base/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Message                `protobuf:"varint,1,opt,name=type,proto3,enum=gateway.v1.Message" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *RawMessage) GetType() Message {
	if x != nil {
		return x.Type
	}
	return Message_MESSAGE_UNSPECIFIED
}

func (x *RawMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SingleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *v1.UUID               `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      *v1.UUID               `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Seq           uint64                 `protobuf:"fixed64,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty" validate:"required"` // 时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleMessage) Reset() {
	*x = SingleMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessage) ProtoMessage() {}

func (x *SingleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessage.ProtoReflect.Descriptor instead.
func (*SingleMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *SingleMessage) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *SingleMessage) GetTargetId() *v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *SingleMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SingleMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// TODO: 暂时不使用,RelayGatewaySingleMessage类型的RawMessage,data直接对应了SingleMessage
type RelayGatewaySingleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayGatewaySingleMessage) Reset() {
	*x = RelayGatewaySingleMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayGatewaySingleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayGatewaySingleMessage) ProtoMessage() {}

func (x *RelayGatewaySingleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayGatewaySingleMessage.ProtoReflect.Descriptor instead.
func (*RelayGatewaySingleMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *RelayGatewaySingleMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *v1.UUID               `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	GroupId       *v1.UUID               `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetId      []*v1.UUID             `protobuf:"bytes,3,rep,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *GroupMessage) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *GroupMessage) GetGroupId() *v1.UUID {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *GroupMessage) GetTargetId() []*v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *GroupMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RelayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *v1.UUID               `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      *v1.UUID               `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SeqId         uint64                 `protobuf:"fixed64,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessage) Reset() {
	*x = RelayMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessage) ProtoMessage() {}

func (x *RelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessage.ProtoReflect.Descriptor instead.
func (*RelayMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *RelayMessage) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *RelayMessage) GetTargetId() *v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *RelayMessage) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *RelayMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{5}
}

type PullMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *v1.UUID               `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`      // 当前用户ID（必填）
	TargetId      *v1.UUID               `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`      // 聊天对象ID（单聊用户ID/群ID）
	LastSeqId     string                 `protobuf:"bytes,3,opt,name=last_seq_id,json=lastSeqId,proto3" json:"last_seq_id,omitempty"` // 上一条消息ID（分页拉取用）
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                           // 拉取数量（默认20）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessage) Reset() {
	*x = PullMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessage) ProtoMessage() {}

func (x *PullMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessage.ProtoReflect.Descriptor instead.
func (*PullMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *PullMessage) GetClientId() *v1.UUID {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *PullMessage) GetTargetId() *v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *PullMessage) GetLastSeqId() string {
	if x != nil {
		return x.LastSeqId
	}
	return ""
}

func (x *PullMessage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ConfirmMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmMessage) Reset() {
	*x = ConfirmMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmMessage) ProtoMessage() {}

func (x *ConfirmMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmMessage.ProtoReflect.Descriptor instead.
func (*ConfirmMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{7}
}

type ReadedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadedMessage) Reset() {
	*x = ReadedMessage{}
	mi := &file_gateway_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadedMessage) ProtoMessage() {}

func (x *ReadedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadedMessage.ProtoReflect.Descriptor instead.
func (*ReadedMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_message_proto_rawDescGZIP(), []int{8}
}

var File_gateway_v1_message_proto protoreflect.FileDescriptor

const file_gateway_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/message.proto\x12\n" +
	"gateway.v1\x1a\x13tagger/tagger.proto\x1a\x12base/v1/uuid.proto\x1a\x18gateway/v1/gateway.proto\"I\n" +
	"\n" +
	"RawMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.gateway.v1.MessageR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xad\x01\n" +
	"\rSingleMessage\x12*\n" +
	"\tsource_id\x18\x01 \x01(\v2\r.base.v1.UUIDR\bsourceId\x12*\n" +
	"\ttarget_id\x18\x02 \x01(\v2\r.base.v1.UUIDR\btargetId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x06R\x03seq\x122\n" +
	"\acontent\x18\x04 \x01(\tB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\acontent\"/\n" +
	"\x19RelayGatewaySingleMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xc4\x01\n" +
	"\fGroupMessage\x12*\n" +
	"\tsource_id\x18\x01 \x01(\v2\r.base.v1.UUIDR\bsourceId\x12(\n" +
	"\bgroup_id\x18\x02 \x01(\v2\r.base.v1.UUIDR\agroupId\x12*\n" +
	"\ttarget_id\x18\x03 \x03(\v2\r.base.v1.UUIDR\btargetId\x122\n" +
	"\acontent\x18\x04 \x01(\tB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\acontent\"\xb1\x01\n" +
	"\fRelayMessage\x12*\n" +
	"\tsource_id\x18\x01 \x01(\v2\r.base.v1.UUIDR\bsourceId\x12*\n" +
	"\ttarget_id\x18\x02 \x01(\v2\r.base.v1.UUIDR\btargetId\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x06R\x05seqId\x122\n" +
	"\acontent\x18\x04 \x01(\tB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\acontent\"\r\n" +
	"\vPushMessage\"\x9b\x01\n" +
	"\vPullMessage\x12*\n" +
	"\tclient_id\x18\x01 \x01(\v2\r.base.v1.UUIDR\bclientId\x12*\n" +
	"\ttarget_id\x18\x02 \x01(\v2\r.base.v1.UUIDR\btargetId\x12\x1e\n" +
	"\vlast_seq_id\x18\x03 \x01(\tR\tlastSeqId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x10\n" +
	"\x0eConfirmMessage\"\x0f\n" +
	"\rReadedMessageB\x94\x01\n" +
	"\x0ecom.gateway.v1B\fMessageProtoP\x01Z+rain-im-server/protogo/gateway/v1;gatewayv1\xa2\x02\x03GXX\xaa\x02\n" +
	"Gateway.V1\xca\x02\n" +
	"Gateway\\V1\xe2\x02\x16Gateway\\V1\\GPBMetadata\xea\x02\vGateway::V1b\x06proto3"

var (
	file_gateway_v1_message_proto_rawDescOnce sync.Once
	file_gateway_v1_message_proto_rawDescData []byte
)

func file_gateway_v1_message_proto_rawDescGZIP() []byte {
	file_gateway_v1_message_proto_rawDescOnce.Do(func() {
		file_gateway_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_message_proto_rawDesc), len(file_gateway_v1_message_proto_rawDesc)))
	})
	return file_gateway_v1_message_proto_rawDescData
}

var file_gateway_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateway_v1_message_proto_goTypes = []any{
	(*RawMessage)(nil),                // 0: gateway.v1.RawMessage
	(*SingleMessage)(nil),             // 1: gateway.v1.SingleMessage
	(*RelayGatewaySingleMessage)(nil), // 2: gateway.v1.RelayGatewaySingleMessage
	(*GroupMessage)(nil),              // 3: gateway.v1.GroupMessage
	(*RelayMessage)(nil),              // 4: gateway.v1.RelayMessage
	(*PushMessage)(nil),               // 5: gateway.v1.PushMessage
	(*PullMessage)(nil),               // 6: gateway.v1.PullMessage
	(*ConfirmMessage)(nil),            // 7: gateway.v1.ConfirmMessage
	(*ReadedMessage)(nil),             // 8: gateway.v1.ReadedMessage
	(Message)(0),                      // 9: gateway.v1.Message
	(*v1.UUID)(nil),                   // 10: base.v1.UUID
}
var file_gateway_v1_message_proto_depIdxs = []int32{
	9,  // 0: gateway.v1.RawMessage.type:type_name -> gateway.v1.Message
	10, // 1: gateway.v1.SingleMessage.source_id:type_name -> base.v1.UUID
	10, // 2: gateway.v1.SingleMessage.target_id:type_name -> base.v1.UUID
	10, // 3: gateway.v1.GroupMessage.source_id:type_name -> base.v1.UUID
	10, // 4: gateway.v1.GroupMessage.group_id:type_name -> base.v1.UUID
	10, // 5: gateway.v1.GroupMessage.target_id:type_name -> base.v1.UUID
	10, // 6: gateway.v1.RelayMessage.source_id:type_name -> base.v1.UUID
	10, // 7: gateway.v1.RelayMessage.target_id:type_name -> base.v1.UUID
	10, // 8: gateway.v1.PullMessage.client_id:type_name -> base.v1.UUID
	10, // 9: gateway.v1.PullMessage.target_id:type_name -> base.v1.UUID
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gateway_v1_message_proto_init() }
func file_gateway_v1_message_proto_init() {
	if File_gateway_v1_message_proto != nil {
		return
	}
	file_gateway_v1_gateway_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_message_proto_rawDesc), len(file_gateway_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_message_proto_goTypes,
		DependencyIndexes: file_gateway_v1_message_proto_depIdxs,
		MessageInfos:      file_gateway_v1_message_proto_msgTypes,
	}.Build()
	File_gateway_v1_message_proto = out.File
	file_gateway_v1_message_proto_goTypes = nil
	file_gateway_v1_message_proto_depIdxs = nil
}
