// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gateway/v1/srv_base.proto

package gatewayv1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "rain-im-server/protogo/base/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsocketConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *v1.UUID               `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Platform      Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=gateway.v1.Platform" json:"platform,omitempty"`
	Token         *string                `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketConnRequest) Reset() {
	*x = WebsocketConnRequest{}
	mi := &file_gateway_v1_srv_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketConnRequest) ProtoMessage() {}

func (x *WebsocketConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_srv_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketConnRequest.ProtoReflect.Descriptor instead.
func (*WebsocketConnRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_srv_base_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketConnRequest) GetClientId() *v1.UUID {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *WebsocketConnRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *WebsocketConnRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type SingleMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *v1.UUID               `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty" validate:"required"`
	TargetId      []*v1.UUID             `protobuf:"bytes,2,rep,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	GroupId       *v1.UUID               `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"` // 群组消息特有
	MessageType   Message                `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=gateway.v1.Message" json:"message_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleMessageRequest) Reset() {
	*x = SingleMessageRequest{}
	mi := &file_gateway_v1_srv_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessageRequest) ProtoMessage() {}

func (x *SingleMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_srv_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessageRequest.ProtoReflect.Descriptor instead.
func (*SingleMessageRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_srv_base_proto_rawDescGZIP(), []int{1}
}

func (x *SingleMessageRequest) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *SingleMessageRequest) GetTargetId() []*v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *SingleMessageRequest) GetGroupId() *v1.UUID {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *SingleMessageRequest) GetMessageType() Message {
	if x != nil {
		return x.MessageType
	}
	return Message_MESSAGE_UNSPECIFIED
}

func (x *SingleMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_gateway_v1_srv_base_proto protoreflect.FileDescriptor

const file_gateway_v1_srv_base_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/v1/srv_base.proto\x12\n" +
	"gateway.v1\x1a\x13tagger/tagger.proto\x1a\x12base/v1/uuid.proto\x1a\x18gateway/v1/gateway.proto\"\x99\x01\n" +
	"\x14WebsocketConnRequest\x12*\n" +
	"\tclient_id\x18\x01 \x01(\v2\r.base.v1.UUIDR\bclientId\x120\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x14.gateway.v1.PlatformR\bplatform\x12\x19\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x88\x01\x01B\b\n" +
	"\x06_token\"\x96\x02\n" +
	"\x14SingleMessageRequest\x12D\n" +
	"\tsource_id\x18\x01 \x01(\v2\r.base.v1.UUIDB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\bsourceId\x12*\n" +
	"\ttarget_id\x18\x02 \x03(\v2\r.base.v1.UUIDR\btargetId\x12-\n" +
	"\bgroup_id\x18\x03 \x01(\v2\r.base.v1.UUIDH\x00R\agroupId\x88\x01\x01\x126\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x13.gateway.v1.MessageR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB\v\n" +
	"\t_group_idB\x94\x01\n" +
	"\x0ecom.gateway.v1B\fSrvBaseProtoP\x01Z+rain-im-server/protogo/gateway/v1;gatewayv1\xa2\x02\x03GXX\xaa\x02\n" +
	"Gateway.V1\xca\x02\n" +
	"Gateway\\V1\xe2\x02\x16Gateway\\V1\\GPBMetadata\xea\x02\vGateway::V1b\x06proto3"

var (
	file_gateway_v1_srv_base_proto_rawDescOnce sync.Once
	file_gateway_v1_srv_base_proto_rawDescData []byte
)

func file_gateway_v1_srv_base_proto_rawDescGZIP() []byte {
	file_gateway_v1_srv_base_proto_rawDescOnce.Do(func() {
		file_gateway_v1_srv_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_srv_base_proto_rawDesc), len(file_gateway_v1_srv_base_proto_rawDesc)))
	})
	return file_gateway_v1_srv_base_proto_rawDescData
}

var file_gateway_v1_srv_base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_v1_srv_base_proto_goTypes = []any{
	(*WebsocketConnRequest)(nil), // 0: gateway.v1.WebsocketConnRequest
	(*SingleMessageRequest)(nil), // 1: gateway.v1.SingleMessageRequest
	(*v1.UUID)(nil),              // 2: base.v1.UUID
	(Platform)(0),                // 3: gateway.v1.Platform
	(Message)(0),                 // 4: gateway.v1.Message
}
var file_gateway_v1_srv_base_proto_depIdxs = []int32{
	2, // 0: gateway.v1.WebsocketConnRequest.client_id:type_name -> base.v1.UUID
	3, // 1: gateway.v1.WebsocketConnRequest.platform:type_name -> gateway.v1.Platform
	2, // 2: gateway.v1.SingleMessageRequest.source_id:type_name -> base.v1.UUID
	2, // 3: gateway.v1.SingleMessageRequest.target_id:type_name -> base.v1.UUID
	2, // 4: gateway.v1.SingleMessageRequest.group_id:type_name -> base.v1.UUID
	4, // 5: gateway.v1.SingleMessageRequest.message_type:type_name -> gateway.v1.Message
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gateway_v1_srv_base_proto_init() }
func file_gateway_v1_srv_base_proto_init() {
	if File_gateway_v1_srv_base_proto != nil {
		return
	}
	file_gateway_v1_gateway_proto_init()
	file_gateway_v1_srv_base_proto_msgTypes[0].OneofWrappers = []any{}
	file_gateway_v1_srv_base_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_srv_base_proto_rawDesc), len(file_gateway_v1_srv_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_srv_base_proto_goTypes,
		DependencyIndexes: file_gateway_v1_srv_base_proto_depIdxs,
		MessageInfos:      file_gateway_v1_srv_base_proto_msgTypes,
	}.Build()
	File_gateway_v1_srv_base_proto = out.File
	file_gateway_v1_srv_base_proto_goTypes = nil
	file_gateway_v1_srv_base_proto_depIdxs = nil
}
