// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gateway/v1/srv_base.proto

package gatewayv1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "rain-im-server/protogo/base/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty" validate:"required"`
	Platform      Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=gateway.v1.Platform" json:"platform,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_gateway_v1_srv_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_srv_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_srv_base_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

type RawMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Message                `protobuf:"varint,1,opt,name=type,proto3,enum=gateway.v1.Message" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	mi := &file_gateway_v1_srv_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_srv_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_srv_base_proto_rawDescGZIP(), []int{1}
}

func (x *RawMessage) GetType() Message {
	if x != nil {
		return x.Type
	}
	return Message_MESSAGE_UNSPECIFIED
}

func (x *RawMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SingleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *v1.UUID               `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty" validate:"required"`
	TargetId      []*v1.UUID             `protobuf:"bytes,2,rep,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	GroupId       *v1.UUID               `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"` // 群组消息特有
	MessageType   Message                `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=gateway.v1.Message" json:"message_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleMessage) Reset() {
	*x = SingleMessage{}
	mi := &file_gateway_v1_srv_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessage) ProtoMessage() {}

func (x *SingleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_srv_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessage.ProtoReflect.Descriptor instead.
func (*SingleMessage) Descriptor() ([]byte, []int) {
	return file_gateway_v1_srv_base_proto_rawDescGZIP(), []int{2}
}

func (x *SingleMessage) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *SingleMessage) GetTargetId() []*v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *SingleMessage) GetGroupId() *v1.UUID {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *SingleMessage) GetMessageType() Message {
	if x != nil {
		return x.MessageType
	}
	return Message_MESSAGE_UNSPECIFIED
}

func (x *SingleMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_gateway_v1_srv_base_proto protoreflect.FileDescriptor

const file_gateway_v1_srv_base_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/v1/srv_base.proto\x12\n" +
	"gateway.v1\x1a\x13tagger/tagger.proto\x1a\x12base/v1/uuid.proto\x1a\x18gateway/v1/gateway.proto\"\x93\x01\n" +
	"\x0eConnectRequest\x125\n" +
	"\tclient_id\x18\x01 \x01(\tB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\bclientId\x12J\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x14.gateway.v1.PlatformB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\bplatform\"I\n" +
	"\n" +
	"RawMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.gateway.v1.MessageR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x8f\x02\n" +
	"\rSingleMessage\x12D\n" +
	"\tsource_id\x18\x01 \x01(\v2\r.base.v1.UUIDB\x18\x9a\x84\x9e\x03\x13validate:\"required\"R\bsourceId\x12*\n" +
	"\ttarget_id\x18\x02 \x03(\v2\r.base.v1.UUIDR\btargetId\x12-\n" +
	"\bgroup_id\x18\x03 \x01(\v2\r.base.v1.UUIDH\x00R\agroupId\x88\x01\x01\x126\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x13.gateway.v1.MessageR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB\v\n" +
	"\t_group_idB\x94\x01\n" +
	"\x0ecom.gateway.v1B\fSrvBaseProtoP\x01Z+rain-im-server/protogo/gateway/v1;gatewayv1\xa2\x02\x03GXX\xaa\x02\n" +
	"Gateway.V1\xca\x02\n" +
	"Gateway\\V1\xe2\x02\x16Gateway\\V1\\GPBMetadata\xea\x02\vGateway::V1b\x06proto3"

var (
	file_gateway_v1_srv_base_proto_rawDescOnce sync.Once
	file_gateway_v1_srv_base_proto_rawDescData []byte
)

func file_gateway_v1_srv_base_proto_rawDescGZIP() []byte {
	file_gateway_v1_srv_base_proto_rawDescOnce.Do(func() {
		file_gateway_v1_srv_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_srv_base_proto_rawDesc), len(file_gateway_v1_srv_base_proto_rawDesc)))
	})
	return file_gateway_v1_srv_base_proto_rawDescData
}

var file_gateway_v1_srv_base_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_v1_srv_base_proto_goTypes = []any{
	(*ConnectRequest)(nil), // 0: gateway.v1.ConnectRequest
	(*RawMessage)(nil),     // 1: gateway.v1.RawMessage
	(*SingleMessage)(nil),  // 2: gateway.v1.SingleMessage
	(Platform)(0),          // 3: gateway.v1.Platform
	(Message)(0),           // 4: gateway.v1.Message
	(*v1.UUID)(nil),        // 5: base.v1.UUID
}
var file_gateway_v1_srv_base_proto_depIdxs = []int32{
	3, // 0: gateway.v1.ConnectRequest.platform:type_name -> gateway.v1.Platform
	4, // 1: gateway.v1.RawMessage.type:type_name -> gateway.v1.Message
	5, // 2: gateway.v1.SingleMessage.source_id:type_name -> base.v1.UUID
	5, // 3: gateway.v1.SingleMessage.target_id:type_name -> base.v1.UUID
	5, // 4: gateway.v1.SingleMessage.group_id:type_name -> base.v1.UUID
	4, // 5: gateway.v1.SingleMessage.message_type:type_name -> gateway.v1.Message
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gateway_v1_srv_base_proto_init() }
func file_gateway_v1_srv_base_proto_init() {
	if File_gateway_v1_srv_base_proto != nil {
		return
	}
	file_gateway_v1_gateway_proto_init()
	file_gateway_v1_srv_base_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_srv_base_proto_rawDesc), len(file_gateway_v1_srv_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_srv_base_proto_goTypes,
		DependencyIndexes: file_gateway_v1_srv_base_proto_depIdxs,
		MessageInfos:      file_gateway_v1_srv_base_proto_msgTypes,
	}.Build()
	File_gateway_v1_srv_base_proto = out.File
	file_gateway_v1_srv_base_proto_goTypes = nil
	file_gateway_v1_srv_base_proto_depIdxs = nil
}
