// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/v1/group.proto

package corev1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "rain-im-server/protogo/base/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.UUID               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bun:"type:uuid,pk"`
	CreatedAt     *v1.Time               `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bun:"type:timestamptz"`
	UpdatedAt     *v1.Time               `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bun:"type:timestamptz"`
	DeletedAt     *v1.Time               `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty" bun:"type:timestamptz,soft_delete,nullzero"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_common_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_common_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() *v1.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Group) GetCreatedAt() *v1.Time {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *v1.Time {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Group) GetDeletedAt() *v1.Time {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_common_v1_group_proto protoreflect.FileDescriptor

const file_common_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/group.proto\x12\acore.v1\x1a\x13tagger/tagger.proto\x1a\x12base/v1/time.proto\x1a\x12base/v1/uuid.proto\"\xc9\x02\n" +
	"\x05Group\x126\n" +
	"\x02id\x18\x01 \x01(\v2\r.base.v1.UUIDB\x17\x9a\x84\x9e\x03\x12bun:\"type:uuid,pk\"R\x02id\x12I\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\r.base.v1.TimeB\x1b\x9a\x84\x9e\x03\x16bun:\"type:timestamptz\"R\tcreatedAt\x12I\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\r.base.v1.TimeB\x1b\x9a\x84\x9e\x03\x16bun:\"type:timestamptz\"R\tupdatedAt\x12c\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\r.base.v1.TimeB0\x9a\x84\x9e\x03+bun:\"type:timestamptz,soft_delete,nullzero\"H\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_atB\x7f\n" +
	"\vcom.core.v1B\n" +
	"GroupProtoP\x01Z'rain-im-server/protogo/common/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_common_v1_group_proto_rawDescOnce sync.Once
	file_common_v1_group_proto_rawDescData []byte
)

func file_common_v1_group_proto_rawDescGZIP() []byte {
	file_common_v1_group_proto_rawDescOnce.Do(func() {
		file_common_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_group_proto_rawDesc), len(file_common_v1_group_proto_rawDesc)))
	})
	return file_common_v1_group_proto_rawDescData
}

var file_common_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_group_proto_goTypes = []any{
	(*Group)(nil),   // 0: core.v1.Group
	(*v1.UUID)(nil), // 1: base.v1.UUID
	(*v1.Time)(nil), // 2: base.v1.Time
}
var file_common_v1_group_proto_depIdxs = []int32{
	1, // 0: core.v1.Group.id:type_name -> base.v1.UUID
	2, // 1: core.v1.Group.created_at:type_name -> base.v1.Time
	2, // 2: core.v1.Group.updated_at:type_name -> base.v1.Time
	2, // 3: core.v1.Group.deleted_at:type_name -> base.v1.Time
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_v1_group_proto_init() }
func file_common_v1_group_proto_init() {
	if File_common_v1_group_proto != nil {
		return
	}
	file_common_v1_group_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_group_proto_rawDesc), len(file_common_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_group_proto_goTypes,
		DependencyIndexes: file_common_v1_group_proto_depIdxs,
		MessageInfos:      file_common_v1_group_proto_msgTypes,
	}.Build()
	File_common_v1_group_proto = out.File
	file_common_v1_group_proto_goTypes = nil
	file_common_v1_group_proto_depIdxs = nil
}
