// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/srv_client.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rain-im-server/protogo/core/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClientServiceName is the fully-qualified name of the ClientService service.
	ClientServiceName = "core.v1.ClientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClientServicePreConnectProcedure is the fully-qualified name of the ClientService's PreConnect
	// RPC.
	ClientServicePreConnectProcedure = "/core.v1.ClientService/PreConnect"
)

// ClientServiceClient is a client for the core.v1.ClientService service.
type ClientServiceClient interface {
	// 预连接,确认client_id存在,提供可使用的msg_gateway
	PreConnect(context.Context, *connect.Request[v1.PreConnectRequest]) (*connect.Response[v1.PreConnectResponse], error)
}

// NewClientServiceClient constructs a client for the core.v1.ClientService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clientServiceMethods := v1.File_core_v1_srv_client_proto.Services().ByName("ClientService").Methods()
	return &clientServiceClient{
		preConnect: connect.NewClient[v1.PreConnectRequest, v1.PreConnectResponse](
			httpClient,
			baseURL+ClientServicePreConnectProcedure,
			connect.WithSchema(clientServiceMethods.ByName("PreConnect")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clientServiceClient implements ClientServiceClient.
type clientServiceClient struct {
	preConnect *connect.Client[v1.PreConnectRequest, v1.PreConnectResponse]
}

// PreConnect calls core.v1.ClientService.PreConnect.
func (c *clientServiceClient) PreConnect(ctx context.Context, req *connect.Request[v1.PreConnectRequest]) (*connect.Response[v1.PreConnectResponse], error) {
	return c.preConnect.CallUnary(ctx, req)
}

// ClientServiceHandler is an implementation of the core.v1.ClientService service.
type ClientServiceHandler interface {
	// 预连接,确认client_id存在,提供可使用的msg_gateway
	PreConnect(context.Context, *connect.Request[v1.PreConnectRequest]) (*connect.Response[v1.PreConnectResponse], error)
}

// NewClientServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClientServiceHandler(svc ClientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clientServiceMethods := v1.File_core_v1_srv_client_proto.Services().ByName("ClientService").Methods()
	clientServicePreConnectHandler := connect.NewUnaryHandler(
		ClientServicePreConnectProcedure,
		svc.PreConnect,
		connect.WithSchema(clientServiceMethods.ByName("PreConnect")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.ClientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClientServicePreConnectProcedure:
			clientServicePreConnectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClientServiceHandler struct{}

func (UnimplementedClientServiceHandler) PreConnect(context.Context, *connect.Request[v1.PreConnectRequest]) (*connect.Response[v1.PreConnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ClientService.PreConnect is not implemented"))
}
