// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/srv_client.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rain-im-server/protogo/core/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClientServiceName is the fully-qualified name of the ClientService service.
	ClientServiceName = "core.v1.ClientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClientServiceSetTokenProcedure is the fully-qualified name of the ClientService's SetToken RPC.
	ClientServiceSetTokenProcedure = "/core.v1.ClientService/SetToken"
	// ClientServiceGetConversationSeqProcedure is the fully-qualified name of the ClientService's
	// GetConversationSeq RPC.
	ClientServiceGetConversationSeqProcedure = "/core.v1.ClientService/GetConversationSeq"
)

// ClientServiceClient is a client for the core.v1.ClientService service.
type ClientServiceClient interface {
	// 确定clientId存在,设置token到缓存再redis中
	SetToken(context.Context, *connect.Request[v1.SetTokenRequest]) (*connect.Response[v1.SetTokenResponse], error)
	GetConversationSeq(context.Context, *connect.Request[v1.GetConversationSeqRequest]) (*connect.Response[v1.GetConversationSeqResponse], error)
}

// NewClientServiceClient constructs a client for the core.v1.ClientService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clientServiceMethods := v1.File_core_v1_srv_client_proto.Services().ByName("ClientService").Methods()
	return &clientServiceClient{
		setToken: connect.NewClient[v1.SetTokenRequest, v1.SetTokenResponse](
			httpClient,
			baseURL+ClientServiceSetTokenProcedure,
			connect.WithSchema(clientServiceMethods.ByName("SetToken")),
			connect.WithClientOptions(opts...),
		),
		getConversationSeq: connect.NewClient[v1.GetConversationSeqRequest, v1.GetConversationSeqResponse](
			httpClient,
			baseURL+ClientServiceGetConversationSeqProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetConversationSeq")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clientServiceClient implements ClientServiceClient.
type clientServiceClient struct {
	setToken           *connect.Client[v1.SetTokenRequest, v1.SetTokenResponse]
	getConversationSeq *connect.Client[v1.GetConversationSeqRequest, v1.GetConversationSeqResponse]
}

// SetToken calls core.v1.ClientService.SetToken.
func (c *clientServiceClient) SetToken(ctx context.Context, req *connect.Request[v1.SetTokenRequest]) (*connect.Response[v1.SetTokenResponse], error) {
	return c.setToken.CallUnary(ctx, req)
}

// GetConversationSeq calls core.v1.ClientService.GetConversationSeq.
func (c *clientServiceClient) GetConversationSeq(ctx context.Context, req *connect.Request[v1.GetConversationSeqRequest]) (*connect.Response[v1.GetConversationSeqResponse], error) {
	return c.getConversationSeq.CallUnary(ctx, req)
}

// ClientServiceHandler is an implementation of the core.v1.ClientService service.
type ClientServiceHandler interface {
	// 确定clientId存在,设置token到缓存再redis中
	SetToken(context.Context, *connect.Request[v1.SetTokenRequest]) (*connect.Response[v1.SetTokenResponse], error)
	GetConversationSeq(context.Context, *connect.Request[v1.GetConversationSeqRequest]) (*connect.Response[v1.GetConversationSeqResponse], error)
}

// NewClientServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClientServiceHandler(svc ClientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clientServiceMethods := v1.File_core_v1_srv_client_proto.Services().ByName("ClientService").Methods()
	clientServiceSetTokenHandler := connect.NewUnaryHandler(
		ClientServiceSetTokenProcedure,
		svc.SetToken,
		connect.WithSchema(clientServiceMethods.ByName("SetToken")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetConversationSeqHandler := connect.NewUnaryHandler(
		ClientServiceGetConversationSeqProcedure,
		svc.GetConversationSeq,
		connect.WithSchema(clientServiceMethods.ByName("GetConversationSeq")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.ClientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClientServiceSetTokenProcedure:
			clientServiceSetTokenHandler.ServeHTTP(w, r)
		case ClientServiceGetConversationSeqProcedure:
			clientServiceGetConversationSeqHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClientServiceHandler struct{}

func (UnimplementedClientServiceHandler) SetToken(context.Context, *connect.Request[v1.SetTokenRequest]) (*connect.Response[v1.SetTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ClientService.SetToken is not implemented"))
}

func (UnimplementedClientServiceHandler) GetConversationSeq(context.Context, *connect.Request[v1.GetConversationSeqRequest]) (*connect.Response[v1.GetConversationSeqResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ClientService.GetConversationSeq is not implemented"))
}
