// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/srv_base.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rain-im-server/protogo/core/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BaseName is the fully-qualified name of the Base service.
	BaseName = "core.v1.Base"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BaseListClientProcedure is the fully-qualified name of the Base's ListClient RPC.
	BaseListClientProcedure = "/core.v1.Base/ListClient"
	// BaseCreateClientProcedure is the fully-qualified name of the Base's CreateClient RPC.
	BaseCreateClientProcedure = "/core.v1.Base/CreateClient"
	// BaseListMessageProcedure is the fully-qualified name of the Base's ListMessage RPC.
	BaseListMessageProcedure = "/core.v1.Base/ListMessage"
	// BaseCreateMessageProcedure is the fully-qualified name of the Base's CreateMessage RPC.
	BaseCreateMessageProcedure = "/core.v1.Base/CreateMessage"
)

// BaseClient is a client for the core.v1.Base service.
type BaseClient interface {
	ListClient(context.Context, *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error)
	CreateClient(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error)
	ListMessage(context.Context, *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error)
	CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error)
}

// NewBaseClient constructs a client for the core.v1.Base service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBaseClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BaseClient {
	baseURL = strings.TrimRight(baseURL, "/")
	baseMethods := v1.File_core_v1_srv_base_proto.Services().ByName("Base").Methods()
	return &baseClient{
		listClient: connect.NewClient[v1.ListClientRequest, v1.ListClientResponse](
			httpClient,
			baseURL+BaseListClientProcedure,
			connect.WithSchema(baseMethods.ByName("ListClient")),
			connect.WithClientOptions(opts...),
		),
		createClient: connect.NewClient[v1.CreateClientRequest, v1.CreateClientResponse](
			httpClient,
			baseURL+BaseCreateClientProcedure,
			connect.WithSchema(baseMethods.ByName("CreateClient")),
			connect.WithClientOptions(opts...),
		),
		listMessage: connect.NewClient[v1.ListMessageRequest, v1.ListMessageResponse](
			httpClient,
			baseURL+BaseListMessageProcedure,
			connect.WithSchema(baseMethods.ByName("ListMessage")),
			connect.WithClientOptions(opts...),
		),
		createMessage: connect.NewClient[v1.CreateMessageRequest, v1.CreateMessageResponse](
			httpClient,
			baseURL+BaseCreateMessageProcedure,
			connect.WithSchema(baseMethods.ByName("CreateMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// baseClient implements BaseClient.
type baseClient struct {
	listClient    *connect.Client[v1.ListClientRequest, v1.ListClientResponse]
	createClient  *connect.Client[v1.CreateClientRequest, v1.CreateClientResponse]
	listMessage   *connect.Client[v1.ListMessageRequest, v1.ListMessageResponse]
	createMessage *connect.Client[v1.CreateMessageRequest, v1.CreateMessageResponse]
}

// ListClient calls core.v1.Base.ListClient.
func (c *baseClient) ListClient(ctx context.Context, req *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error) {
	return c.listClient.CallUnary(ctx, req)
}

// CreateClient calls core.v1.Base.CreateClient.
func (c *baseClient) CreateClient(ctx context.Context, req *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error) {
	return c.createClient.CallUnary(ctx, req)
}

// ListMessage calls core.v1.Base.ListMessage.
func (c *baseClient) ListMessage(ctx context.Context, req *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error) {
	return c.listMessage.CallUnary(ctx, req)
}

// CreateMessage calls core.v1.Base.CreateMessage.
func (c *baseClient) CreateMessage(ctx context.Context, req *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	return c.createMessage.CallUnary(ctx, req)
}

// BaseHandler is an implementation of the core.v1.Base service.
type BaseHandler interface {
	ListClient(context.Context, *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error)
	CreateClient(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error)
	ListMessage(context.Context, *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error)
	CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error)
}

// NewBaseHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBaseHandler(svc BaseHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	baseMethods := v1.File_core_v1_srv_base_proto.Services().ByName("Base").Methods()
	baseListClientHandler := connect.NewUnaryHandler(
		BaseListClientProcedure,
		svc.ListClient,
		connect.WithSchema(baseMethods.ByName("ListClient")),
		connect.WithHandlerOptions(opts...),
	)
	baseCreateClientHandler := connect.NewUnaryHandler(
		BaseCreateClientProcedure,
		svc.CreateClient,
		connect.WithSchema(baseMethods.ByName("CreateClient")),
		connect.WithHandlerOptions(opts...),
	)
	baseListMessageHandler := connect.NewUnaryHandler(
		BaseListMessageProcedure,
		svc.ListMessage,
		connect.WithSchema(baseMethods.ByName("ListMessage")),
		connect.WithHandlerOptions(opts...),
	)
	baseCreateMessageHandler := connect.NewUnaryHandler(
		BaseCreateMessageProcedure,
		svc.CreateMessage,
		connect.WithSchema(baseMethods.ByName("CreateMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.Base/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BaseListClientProcedure:
			baseListClientHandler.ServeHTTP(w, r)
		case BaseCreateClientProcedure:
			baseCreateClientHandler.ServeHTTP(w, r)
		case BaseListMessageProcedure:
			baseListMessageHandler.ServeHTTP(w, r)
		case BaseCreateMessageProcedure:
			baseCreateMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBaseHandler returns CodeUnimplemented from all methods.
type UnimplementedBaseHandler struct{}

func (UnimplementedBaseHandler) ListClient(context.Context, *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.Base.ListClient is not implemented"))
}

func (UnimplementedBaseHandler) CreateClient(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.Base.CreateClient is not implemented"))
}

func (UnimplementedBaseHandler) ListMessage(context.Context, *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.Base.ListMessage is not implemented"))
}

func (UnimplementedBaseHandler) CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.Base.CreateMessage is not implemented"))
}
