// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/srv_message.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rain-im-server/protogo/core/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MessageServiceName is the fully-qualified name of the MessageService service.
	MessageServiceName = "core.v1.MessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MessageServiceListMessageBySeqProcedure is the fully-qualified name of the MessageService's
	// ListMessageBySeq RPC.
	MessageServiceListMessageBySeqProcedure = "/core.v1.MessageService/ListMessageBySeq"
)

// MessageServiceClient is a client for the core.v1.MessageService service.
type MessageServiceClient interface {
	ListMessageBySeq(context.Context, *connect.Request[v1.ListMessageBySeqRequest]) (*connect.Response[v1.ListMessageBySeqResponse], error)
}

// NewMessageServiceClient constructs a client for the core.v1.MessageService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	messageServiceMethods := v1.File_core_v1_srv_message_proto.Services().ByName("MessageService").Methods()
	return &messageServiceClient{
		listMessageBySeq: connect.NewClient[v1.ListMessageBySeqRequest, v1.ListMessageBySeqResponse](
			httpClient,
			baseURL+MessageServiceListMessageBySeqProcedure,
			connect.WithSchema(messageServiceMethods.ByName("ListMessageBySeq")),
			connect.WithClientOptions(opts...),
		),
	}
}

// messageServiceClient implements MessageServiceClient.
type messageServiceClient struct {
	listMessageBySeq *connect.Client[v1.ListMessageBySeqRequest, v1.ListMessageBySeqResponse]
}

// ListMessageBySeq calls core.v1.MessageService.ListMessageBySeq.
func (c *messageServiceClient) ListMessageBySeq(ctx context.Context, req *connect.Request[v1.ListMessageBySeqRequest]) (*connect.Response[v1.ListMessageBySeqResponse], error) {
	return c.listMessageBySeq.CallUnary(ctx, req)
}

// MessageServiceHandler is an implementation of the core.v1.MessageService service.
type MessageServiceHandler interface {
	ListMessageBySeq(context.Context, *connect.Request[v1.ListMessageBySeqRequest]) (*connect.Response[v1.ListMessageBySeqResponse], error)
}

// NewMessageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMessageServiceHandler(svc MessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	messageServiceMethods := v1.File_core_v1_srv_message_proto.Services().ByName("MessageService").Methods()
	messageServiceListMessageBySeqHandler := connect.NewUnaryHandler(
		MessageServiceListMessageBySeqProcedure,
		svc.ListMessageBySeq,
		connect.WithSchema(messageServiceMethods.ByName("ListMessageBySeq")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.MessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MessageServiceListMessageBySeqProcedure:
			messageServiceListMessageBySeqHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMessageServiceHandler struct{}

func (UnimplementedMessageServiceHandler) ListMessageBySeq(context.Context, *connect.Request[v1.ListMessageBySeqRequest]) (*connect.Response[v1.ListMessageBySeqResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.MessageService.ListMessageBySeq is not implemented"))
}
