// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/srv_base.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rain-im-server/protogo/core/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BaseServiceName is the fully-qualified name of the BaseService service.
	BaseServiceName = "core.v1.BaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BaseServiceListClientProcedure is the fully-qualified name of the BaseService's ListClient RPC.
	BaseServiceListClientProcedure = "/core.v1.BaseService/ListClient"
	// BaseServiceCreateClientProcedure is the fully-qualified name of the BaseService's CreateClient
	// RPC.
	BaseServiceCreateClientProcedure = "/core.v1.BaseService/CreateClient"
	// BaseServiceListMessageProcedure is the fully-qualified name of the BaseService's ListMessage RPC.
	BaseServiceListMessageProcedure = "/core.v1.BaseService/ListMessage"
	// BaseServiceCreateMessageProcedure is the fully-qualified name of the BaseService's CreateMessage
	// RPC.
	BaseServiceCreateMessageProcedure = "/core.v1.BaseService/CreateMessage"
)

// BaseServiceClient is a client for the core.v1.BaseService service.
type BaseServiceClient interface {
	ListClient(context.Context, *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error)
	CreateClient(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error)
	ListMessage(context.Context, *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error)
	CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error)
}

// NewBaseServiceClient constructs a client for the core.v1.BaseService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	baseServiceMethods := v1.File_core_v1_srv_base_proto.Services().ByName("BaseService").Methods()
	return &baseServiceClient{
		listClient: connect.NewClient[v1.ListClientRequest, v1.ListClientResponse](
			httpClient,
			baseURL+BaseServiceListClientProcedure,
			connect.WithSchema(baseServiceMethods.ByName("ListClient")),
			connect.WithClientOptions(opts...),
		),
		createClient: connect.NewClient[v1.CreateClientRequest, v1.CreateClientResponse](
			httpClient,
			baseURL+BaseServiceCreateClientProcedure,
			connect.WithSchema(baseServiceMethods.ByName("CreateClient")),
			connect.WithClientOptions(opts...),
		),
		listMessage: connect.NewClient[v1.ListMessageRequest, v1.ListMessageResponse](
			httpClient,
			baseURL+BaseServiceListMessageProcedure,
			connect.WithSchema(baseServiceMethods.ByName("ListMessage")),
			connect.WithClientOptions(opts...),
		),
		createMessage: connect.NewClient[v1.CreateMessageRequest, v1.CreateMessageResponse](
			httpClient,
			baseURL+BaseServiceCreateMessageProcedure,
			connect.WithSchema(baseServiceMethods.ByName("CreateMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// baseServiceClient implements BaseServiceClient.
type baseServiceClient struct {
	listClient    *connect.Client[v1.ListClientRequest, v1.ListClientResponse]
	createClient  *connect.Client[v1.CreateClientRequest, v1.CreateClientResponse]
	listMessage   *connect.Client[v1.ListMessageRequest, v1.ListMessageResponse]
	createMessage *connect.Client[v1.CreateMessageRequest, v1.CreateMessageResponse]
}

// ListClient calls core.v1.BaseService.ListClient.
func (c *baseServiceClient) ListClient(ctx context.Context, req *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error) {
	return c.listClient.CallUnary(ctx, req)
}

// CreateClient calls core.v1.BaseService.CreateClient.
func (c *baseServiceClient) CreateClient(ctx context.Context, req *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error) {
	return c.createClient.CallUnary(ctx, req)
}

// ListMessage calls core.v1.BaseService.ListMessage.
func (c *baseServiceClient) ListMessage(ctx context.Context, req *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error) {
	return c.listMessage.CallUnary(ctx, req)
}

// CreateMessage calls core.v1.BaseService.CreateMessage.
func (c *baseServiceClient) CreateMessage(ctx context.Context, req *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	return c.createMessage.CallUnary(ctx, req)
}

// BaseServiceHandler is an implementation of the core.v1.BaseService service.
type BaseServiceHandler interface {
	ListClient(context.Context, *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error)
	CreateClient(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error)
	ListMessage(context.Context, *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error)
	CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error)
}

// NewBaseServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBaseServiceHandler(svc BaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	baseServiceMethods := v1.File_core_v1_srv_base_proto.Services().ByName("BaseService").Methods()
	baseServiceListClientHandler := connect.NewUnaryHandler(
		BaseServiceListClientProcedure,
		svc.ListClient,
		connect.WithSchema(baseServiceMethods.ByName("ListClient")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceCreateClientHandler := connect.NewUnaryHandler(
		BaseServiceCreateClientProcedure,
		svc.CreateClient,
		connect.WithSchema(baseServiceMethods.ByName("CreateClient")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceListMessageHandler := connect.NewUnaryHandler(
		BaseServiceListMessageProcedure,
		svc.ListMessage,
		connect.WithSchema(baseServiceMethods.ByName("ListMessage")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceCreateMessageHandler := connect.NewUnaryHandler(
		BaseServiceCreateMessageProcedure,
		svc.CreateMessage,
		connect.WithSchema(baseServiceMethods.ByName("CreateMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.BaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BaseServiceListClientProcedure:
			baseServiceListClientHandler.ServeHTTP(w, r)
		case BaseServiceCreateClientProcedure:
			baseServiceCreateClientHandler.ServeHTTP(w, r)
		case BaseServiceListMessageProcedure:
			baseServiceListMessageHandler.ServeHTTP(w, r)
		case BaseServiceCreateMessageProcedure:
			baseServiceCreateMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBaseServiceHandler struct{}

func (UnimplementedBaseServiceHandler) ListClient(context.Context, *connect.Request[v1.ListClientRequest]) (*connect.Response[v1.ListClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.BaseService.ListClient is not implemented"))
}

func (UnimplementedBaseServiceHandler) CreateClient(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.BaseService.CreateClient is not implemented"))
}

func (UnimplementedBaseServiceHandler) ListMessage(context.Context, *connect.Request[v1.ListMessageRequest]) (*connect.Response[v1.ListMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.BaseService.ListMessage is not implemented"))
}

func (UnimplementedBaseServiceHandler) CreateMessage(context.Context, *connect.Request[v1.CreateMessageRequest]) (*connect.Response[v1.CreateMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.BaseService.CreateMessage is not implemented"))
}
