// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: base/v1/query.proto

package basev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_base_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_base_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []*SortKey             `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_base_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_base_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *Sort) GetKey() []*SortKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type SortKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*SortKey_Asc
	//	*SortKey_Desc
	Key           isSortKey_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortKey) Reset() {
	*x = SortKey{}
	mi := &file_base_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortKey) ProtoMessage() {}

func (x *SortKey) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortKey.ProtoReflect.Descriptor instead.
func (*SortKey) Descriptor() ([]byte, []int) {
	return file_base_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *SortKey) GetKey() isSortKey_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SortKey) GetAsc() string {
	if x != nil {
		if x, ok := x.Key.(*SortKey_Asc); ok {
			return x.Asc
		}
	}
	return ""
}

func (x *SortKey) GetDesc() string {
	if x != nil {
		if x, ok := x.Key.(*SortKey_Desc); ok {
			return x.Desc
		}
	}
	return ""
}

type isSortKey_Key interface {
	isSortKey_Key()
}

type SortKey_Asc struct {
	Asc string `protobuf:"bytes,1,opt,name=asc,proto3,oneof"`
}

type SortKey_Desc struct {
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3,oneof"`
}

func (*SortKey_Asc) isSortKey_Key() {}

func (*SortKey_Desc) isSortKey_Key() {}

var File_base_v1_query_proto protoreflect.FileDescriptor

const file_base_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x13base/v1/query.proto\x12\abase.v1\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"*\n" +
	"\x04Sort\x12\"\n" +
	"\x03key\x18\x01 \x03(\v2\x10.base.v1.SortKeyR\x03key\":\n" +
	"\aSortKey\x12\x12\n" +
	"\x03asc\x18\x01 \x01(\tH\x00R\x03asc\x12\x14\n" +
	"\x04desc\x18\x02 \x01(\tH\x00R\x04descB\x05\n" +
	"\x03keyB}\n" +
	"\vcom.base.v1B\n" +
	"QueryProtoP\x01Z%rain-im-server/protogo/base/v1;basev1\xa2\x02\x03BXX\xaa\x02\aBase.V1\xca\x02\aBase\\V1\xe2\x02\x13Base\\V1\\GPBMetadata\xea\x02\bBase::V1b\x06proto3"

var (
	file_base_v1_query_proto_rawDescOnce sync.Once
	file_base_v1_query_proto_rawDescData []byte
)

func file_base_v1_query_proto_rawDescGZIP() []byte {
	file_base_v1_query_proto_rawDescOnce.Do(func() {
		file_base_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_query_proto_rawDesc), len(file_base_v1_query_proto_rawDesc)))
	})
	return file_base_v1_query_proto_rawDescData
}

var file_base_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_base_v1_query_proto_goTypes = []any{
	(*Pagination)(nil), // 0: base.v1.Pagination
	(*Sort)(nil),       // 1: base.v1.Sort
	(*SortKey)(nil),    // 2: base.v1.SortKey
}
var file_base_v1_query_proto_depIdxs = []int32{
	2, // 0: base.v1.Sort.key:type_name -> base.v1.SortKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_v1_query_proto_init() }
func file_base_v1_query_proto_init() {
	if File_base_v1_query_proto != nil {
		return
	}
	file_base_v1_query_proto_msgTypes[2].OneofWrappers = []any{
		(*SortKey_Asc)(nil),
		(*SortKey_Desc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_query_proto_rawDesc), len(file_base_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_v1_query_proto_goTypes,
		DependencyIndexes: file_base_v1_query_proto_depIdxs,
		MessageInfos:      file_base_v1_query_proto_msgTypes,
	}.Build()
	File_base_v1_query_proto = out.File
	file_base_v1_query_proto_goTypes = nil
	file_base_v1_query_proto_depIdxs = nil
}
