// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: base/v1/uuid.proto

package basev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A UUID, encoded in accordance with section 4.1.2 of RFC 4122.
type UUID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The high 64 bits of the UUID - MSB -> LSB: time_low (32 bits) | time_mid (16 bits) | time_hi_and_version (16 bits).
	Hi uint64 `protobuf:"fixed64,1,opt,name=hi,proto3" json:"hi,omitempty"`
	// The low 64 bits of the UUID - MSB -> LSB: clock_seq_hi_and_reserved (8 bits) | clock_seq_low (8 bits) | node (48 bits).
	Lo            uint64 `protobuf:"fixed64,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_base_v1_uuid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_uuid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_base_v1_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

func (x *UUID) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

var File_base_v1_uuid_proto protoreflect.FileDescriptor

const file_base_v1_uuid_proto_rawDesc = "" +
	"\n" +
	"\x12base/v1/uuid.proto\x12\abase.v1\"&\n" +
	"\x04UUID\x12\x0e\n" +
	"\x02hi\x18\x01 \x01(\x06R\x02hi\x12\x0e\n" +
	"\x02lo\x18\x02 \x01(\x06R\x02loB|\n" +
	"\vcom.base.v1B\tUuidProtoP\x01Z%rain-im-server/protogo/base/v1;basev1\xa2\x02\x03BXX\xaa\x02\aBase.V1\xca\x02\aBase\\V1\xe2\x02\x13Base\\V1\\GPBMetadata\xea\x02\bBase::V1b\x06proto3"

var (
	file_base_v1_uuid_proto_rawDescOnce sync.Once
	file_base_v1_uuid_proto_rawDescData []byte
)

func file_base_v1_uuid_proto_rawDescGZIP() []byte {
	file_base_v1_uuid_proto_rawDescOnce.Do(func() {
		file_base_v1_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_uuid_proto_rawDesc), len(file_base_v1_uuid_proto_rawDesc)))
	})
	return file_base_v1_uuid_proto_rawDescData
}

var file_base_v1_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_v1_uuid_proto_goTypes = []any{
	(*UUID)(nil), // 0: base.v1.UUID
}
var file_base_v1_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_v1_uuid_proto_init() }
func file_base_v1_uuid_proto_init() {
	if File_base_v1_uuid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_uuid_proto_rawDesc), len(file_base_v1_uuid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_v1_uuid_proto_goTypes,
		DependencyIndexes: file_base_v1_uuid_proto_depIdxs,
		MessageInfos:      file_base_v1_uuid_proto_msgTypes,
	}.Build()
	File_base_v1_uuid_proto = out.File
	file_base_v1_uuid_proto_goTypes = nil
	file_base_v1_uuid_proto_depIdxs = nil
}
