// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/v1/srv_message.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "rain-im-server/protogo/base/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_OLDER       Direction = 1 // 拉取更早的
	Direction_DIRECTION_NEWER       Direction = 2 // 拉取更新的
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_OLDER",
		2: "DIRECTION_NEWER",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_OLDER":       1,
		"DIRECTION_NEWER":       2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_srv_message_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_core_v1_srv_message_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_srv_message_proto_rawDescGZIP(), []int{0}
}

type ListMessageBySeqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *v1.UUID               `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      *v1.UUID               `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Seq           uint64                 `protobuf:"fixed64,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=core.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageBySeqRequest) Reset() {
	*x = ListMessageBySeqRequest{}
	mi := &file_core_v1_srv_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageBySeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageBySeqRequest) ProtoMessage() {}

func (x *ListMessageBySeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_srv_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageBySeqRequest.ProtoReflect.Descriptor instead.
func (*ListMessageBySeqRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_srv_message_proto_rawDescGZIP(), []int{0}
}

func (x *ListMessageBySeqRequest) GetSourceId() *v1.UUID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *ListMessageBySeqRequest) GetTargetId() *v1.UUID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *ListMessageBySeqRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ListMessageBySeqRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessageBySeqRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type ListMessageBySeqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Message             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageBySeqResponse) Reset() {
	*x = ListMessageBySeqResponse{}
	mi := &file_core_v1_srv_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageBySeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageBySeqResponse) ProtoMessage() {}

func (x *ListMessageBySeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_srv_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageBySeqResponse.ProtoReflect.Descriptor instead.
func (*ListMessageBySeqResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_srv_message_proto_rawDescGZIP(), []int{1}
}

func (x *ListMessageBySeqResponse) GetData() []*Message {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListMessageBySeqResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_core_v1_srv_message_proto protoreflect.FileDescriptor

const file_core_v1_srv_message_proto_rawDesc = "" +
	"\n" +
	"\x19core/v1/srv_message.proto\x12\acore.v1\x1a\x12base/v1/uuid.proto\x1a\x15core/v1/message.proto\"\xcb\x01\n" +
	"\x17ListMessageBySeqRequest\x12*\n" +
	"\tsource_id\x18\x01 \x01(\v2\r.base.v1.UUIDR\bsourceId\x12*\n" +
	"\ttarget_id\x18\x02 \x01(\v2\r.base.v1.UUIDR\btargetId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x06R\x03seq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x120\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x12.core.v1.DirectionR\tdirection\"V\n" +
	"\x18ListMessageBySeqResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.core.v1.MessageR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count*P\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIRECTION_OLDER\x10\x01\x12\x13\n" +
	"\x0fDIRECTION_NEWER\x10\x022k\n" +
	"\x0eMessageService\x12Y\n" +
	"\x10ListMessageBySeq\x12 .core.v1.ListMessageBySeqRequest\x1a!.core.v1.ListMessageBySeqResponse\"\x00B\x82\x01\n" +
	"\vcom.core.v1B\x0fSrvMessageProtoP\x01Z%rain-im-server/protogo/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_srv_message_proto_rawDescOnce sync.Once
	file_core_v1_srv_message_proto_rawDescData []byte
)

func file_core_v1_srv_message_proto_rawDescGZIP() []byte {
	file_core_v1_srv_message_proto_rawDescOnce.Do(func() {
		file_core_v1_srv_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_srv_message_proto_rawDesc), len(file_core_v1_srv_message_proto_rawDesc)))
	})
	return file_core_v1_srv_message_proto_rawDescData
}

var file_core_v1_srv_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_v1_srv_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_srv_message_proto_goTypes = []any{
	(Direction)(0),                   // 0: core.v1.Direction
	(*ListMessageBySeqRequest)(nil),  // 1: core.v1.ListMessageBySeqRequest
	(*ListMessageBySeqResponse)(nil), // 2: core.v1.ListMessageBySeqResponse
	(*v1.UUID)(nil),                  // 3: base.v1.UUID
	(*Message)(nil),                  // 4: core.v1.Message
}
var file_core_v1_srv_message_proto_depIdxs = []int32{
	3, // 0: core.v1.ListMessageBySeqRequest.source_id:type_name -> base.v1.UUID
	3, // 1: core.v1.ListMessageBySeqRequest.target_id:type_name -> base.v1.UUID
	0, // 2: core.v1.ListMessageBySeqRequest.direction:type_name -> core.v1.Direction
	4, // 3: core.v1.ListMessageBySeqResponse.data:type_name -> core.v1.Message
	1, // 4: core.v1.MessageService.ListMessageBySeq:input_type -> core.v1.ListMessageBySeqRequest
	2, // 5: core.v1.MessageService.ListMessageBySeq:output_type -> core.v1.ListMessageBySeqResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_v1_srv_message_proto_init() }
func file_core_v1_srv_message_proto_init() {
	if File_core_v1_srv_message_proto != nil {
		return
	}
	file_core_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_srv_message_proto_rawDesc), len(file_core_v1_srv_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_srv_message_proto_goTypes,
		DependencyIndexes: file_core_v1_srv_message_proto_depIdxs,
		EnumInfos:         file_core_v1_srv_message_proto_enumTypes,
		MessageInfos:      file_core_v1_srv_message_proto_msgTypes,
	}.Build()
	File_core_v1_srv_message_proto = out.File
	file_core_v1_srv_message_proto_goTypes = nil
	file_core_v1_srv_message_proto_depIdxs = nil
}
