syntax = "proto3";
package core.v1;

import "tagger/tagger.proto";
import "base/v1/time.proto";
import "base/v1/uuid.proto";

message Client {
    base.v1.UUID id                  = 1 [(tagger.tags) = "bun:\"type:uuid,pk\""];
    ClientType   type                = 2;
    base.v1.Time created_at          = 3 [(tagger.tags) = "bun:\"type:timestamptz\""];
    base.v1.Time updated_at          = 4 [(tagger.tags) = "bun:\"type:timestamptz\""];
    optional base.v1.Time deleted_at = 5 [(tagger.tags) = "bun:\"type:timestamptz,soft_delete,nullzero\""];
}

enum ClientType {
    CLIENT_TYPE_UNSPECIFIED = 0;
    CLIENT_TYPE_SYSTEM      = 1;
    CLIENT_TYPE_USER        = 2;
    CLIENT_TYPE_GROUP       = 3;
}

message ClientConversation {
    base.v1.UUID id         = 1 [(tagger.tags) = "bun:\"type:uuid,pk\""];
    base.v1.UUID client_min = 2 [(tagger.tags) = "bun:\"type:uuid\""];
    base.v1.UUID client_max = 3 [(tagger.tags) = "bun:\"type:uuid\""];
    fixed64      seq        = 4;
    base.v1.Time created_at = 5 [(tagger.tags) = "bun:\"type:timestamptz\""];
}

message ClientGroupConversation {
    base.v1.UUID id         = 1 [(tagger.tags) = "bun:\"type:uuid,pk\""];
    base.v1.UUID group_id   = 2 [(tagger.tags) = "bun:\"type:uuid\""];
    fixed64      seq        = 3;
    base.v1.Time created_at = 4 [(tagger.tags) = "bun:\"type:timestamptz\""];
}