syntax = "proto3";
package gateway.v1;

enum Platform {
    PLATFORM_UNSPECIFIED = 0;
    PLATFORM_SYSTEM      = 1;  // 系统
    PLATFORM_WEB         = 2;  // 网页
    PLATFORM_ANDROID     = 3;  // 安卓
    PLATFORM_IPHONE      = 4;  // 苹果
    PLATFORM_WINDOWS     = 5;  // Windows
    PLATFORM_MACOS       = 6;  // Mac
    PLATFORM_LINUX       = 7;  // Linux
}

enum Message {
    MESSAGE_UNSPECIFIED = 0;
    MESSAGE_CONNECT     = 1;  // 连接消息
    MESSAGE_SINGLE      = 2;  // 单发
    MESSAGE_GROUP       = 3;  // 群发
    MESSAGE_PUSH        = 4;  // 推送消息
    MESSAGE_PULL        = 5;  // 拉取消息
    MESSAGE_CONFIRM     = 6;  // TODO:确认消息
    MESSAGE_READED      = 7;  // TODO:已读消息
}

// 推送消息:单发和群发消息没有seq_id,推送消息有,不用持久化直接传递。由单发和群发消息转换而来