syntax = "proto3";
package gateway.v1;

import "tagger/tagger.proto";
import "base/v1/uuid.proto";
import "gateway/v1/gateway.proto";

message ConnectRequest {
    string   client_id = 1 [(tagger.tags) = "validate:\"required\""];
    Platform platform  = 2 [(tagger.tags) = "validate:\"required\""];
}
// 这里不用去数据库查询client_id,所有传递字符串
// 对token进行规范设计后,client_id、platform直接包含在token中

message RawMessage {
    Message type = 1;
    bytes   data = 2;
}

message SingleMessage {
    base.v1.UUID source_id             = 1 [(tagger.tags) = "validate:\"required\""];
    repeated base.v1.UUID target_id    = 2;
    optional base.v1.UUID group_id     = 3;  // 群组消息特有
    Message               message_type = 4;
    string                content      = 5;
}